import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const popines= Poppins({
  subsets:['latin'],
  display: 'swap',
  variable:'--font-popines',
  weight:['100','200','300','400','500','600','700','800','900']


})

export const metadata = {
  title: "Real Estate Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={popines.className}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
